/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capg;

//import org.junit.Test;

//import com.capgemini.AddressBookMain;

//import static org.junit.Assert.*;

public class AddressBookMainTest {
 //   @Test public void testSomeLibraryMethod() {
    //    AddressBookMain classUnderTest = new AddressBookMain();
   //     assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  //  }
}
