/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini;

public class AddressBookMain {
   public static void main(String[] args) {
	System.out.println("Welcome to Address Book Program");
    }
}
