/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini;

import com.capgemini.dto.AddressBook;
//import com.capgemini.service.*;
//import com.capgemini.service.implementation.*;

public class AddressBookMain {
   public static void main(String[] args) {
	System.out.println("Welcome to Address Book Program");
	AddressBook addressBook = new AddressBook();
	addressBook.addPerson();
    }
}
